---
- name: Build and install dcgm-exporter and package as .deb
  hosts: local
  become: yes
  vars:
    dcgm_dir: /tmp/dcgm-exporter
    go_root: /usr/local/go
    go_path: /usr/local/go/bin:/usr/local/bin:/usr/bin:/bin
    pkg_name: dcgm-exporter
    pkg_version: "1.0.0"
    pkg_output: "/opt/staging/{{ pkg_name }}_{{ pkg_version }}.deb"

  tasks:
    - name: Ensure dcgm_exporter_status fact is set
      setup:
      tags: always

    - name: Install DCGM Exporter
      block:
        - name: Force remove existing DCGM Exporter directory if it exists
          file:
            path: "{{ dcgm_dir }}"
            state: absent
          ignore_errors: yes

        - name: Clone DCGM Exporter repository (force clean clone)
          git:
            repo: https://github.com/NVIDIA/dcgm-exporter.git
            dest: "{{ dcgm_dir }}"
            force: yes

        - name: Build and install DCGM Exporter with GOROOT and PATH set
          command: make install
          args:
            chdir: "{{ dcgm_dir }}"
          environment:
            GOROOT: "{{ go_root }}"
            PATH: "{{ go_path }}"

        - name: Create DCGM Exporter systemd service
          copy:
            content: |
              [Unit]
              Description=dcgm Exporter
              [Service]
              ExecStart=/usr/bin/dcgm-exporter
              Restart=on-failure
              RestartSec=15
              Type=simple
              [Install]
              WantedBy=multi-user.target
            dest: /etc/systemd/system/dcgm-exporter.service
            mode: '0644'

        - name: Reload systemd and start DCGM Exporter service
          systemd:
            daemon_reload: yes
            name: dcgm-exporter
            enabled: yes
            state: started

    - name: Create package directory structure
      file:
        path: "/tmp/{{ pkg_name }}_pkg/usr/bin"
        state: directory
        mode: '0755'
        recurse: yes

    - name: Create DEBIAN directory
      file: 
        path: "/tmp/{{ pkg_name }}_pkg/DEBIAN"
        state: directory
        mode: '0755'

    - name: Copy built binary to package folder
      copy:
        src: "/usr/bin/dcgm-exporter"
        dest: "/tmp/{{ pkg_name }}_pkg/usr/bin/dcgm-exporter"
        mode: '0755'

    - name: Create DEBIAN control file
      copy:
        dest: "/tmp/{{ pkg_name }}_pkg/DEBIAN/control"
        content: |
          Package: {{ pkg_name }}
          Version: {{ pkg_version }}
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: james@stninc.com
          Description: Custom-built dcgm-exporter

    - name: Ensure staging dir exists
      file:
        path: "/opt/staging"
        state: directory
        mode: '0755'
        
    - name: Build .deb package
      command: >
        dpkg-deb --build /tmp/{{ pkg_name }}_pkg {{ pkg_output }}

    - name: Move .deb package to staging
      copy:
        src: "{{ pkg_output }}"
        dest: "/opt/staging/"
        remote_src: yes
